name: ci
on: push

jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: ".nvmrc"

      - name: Install
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Check size
        run: yarn size
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: ".nvmrc"

      - name: Install
        run: yarn install --immutable

      - name: Jest
        run: yarn test
